<a href="https://colab.research.google.com/github/sankalp24/pytorch_tutorial/blob/master/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x = torch.randn(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

tensor([[-0.1169, -0.6118],
        [ 0.0098,  0.2701]], requires_grad=True)
True


In [3]:
y = x + 2
print(y)
print(y.requires_grad)

tensor([[1.8831, 1.3882],
        [2.0098, 2.2701]], grad_fn=<AddBackward0>)
True


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)
print(z.requires_grad)
print(out)

tensor([[10.6378,  5.7811],
        [12.1176, 15.4599]], grad_fn=<MulBackward0>) tensor(10.9991, grad_fn=<MeanBackward0>)
True
tensor(10.9991, grad_fn=<MeanBackward0>)


In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(b.requires_grad)

False
True
True


In [0]:
out.backward()

In [8]:
print(x.grad)

tensor([[2.8246, 2.0823],
        [3.0147, 3.4051]])


In [9]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-512.1947, -224.3180, 1630.8907], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [12]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [13]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())


True
False
tensor(True)
