<a href="https://colab.research.google.com/github/sankalp24/pytorch_tutorial/blob/master/pytorch_tp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
x = torch.empty(5, 3)
print(x)


tensor([[1.6231e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [0]:
x = torch.rand(5, 3)
print(x)


tensor([[0.4476, 0.7592, 0.8790],
        [0.3919, 0.2564, 0.4235],
        [0.9211, 0.6965, 0.4386],
        [0.7393, 0.5366, 0.2257],
        [0.9123, 0.9751, 0.2852]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)    

tensor([[-1.0253,  1.6412, -0.4841],
        [ 0.6972, -0.5882,  1.2751],
        [-0.9655, -1.5591, -0.7863],
        [ 0.5113, -0.7911,  1.2207],
        [ 0.5734,  1.7052, -0.0063]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-1.0253,  1.6412, -0.4841],
        [ 0.6972, -0.5882,  1.2751],
        [-0.9655, -1.5591, -0.7863],
        [ 0.5113, -0.7911,  1.2207],
        [ 0.5734,  1.7052, -0.0063]])
tensor([[0.1735, 0.0849, 0.6912],
        [0.0591, 0.1204, 0.0126],
        [0.4346, 0.0368, 0.3998],
        [0.3963, 0.4976, 0.1797],
        [0.3656, 0.2869, 0.3269]])
tensor([[-0.8518,  1.7260,  0.2071],
        [ 0.7564, -0.4678,  1.2877],
        [-0.5309, -1.5223, -0.3864],
        [ 0.9076, -0.2934,  1.4004],
        [ 0.9390,  1.9920,  0.3206]])


In [0]:
print(torch.add(x, y))

tensor([[-0.8518,  1.7260,  0.2071],
        [ 0.7564, -0.4678,  1.2877],
        [-0.5309, -1.5223, -0.3864],
        [ 0.9076, -0.2934,  1.4004],
        [ 0.9390,  1.9920,  0.3206]])


In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.8518,  1.7260,  0.2071],
        [ 0.7564, -0.4678,  1.2877],
        [-0.5309, -1.5223, -0.3864],
        [ 0.9076, -0.2934,  1.4004],
        [ 0.9390,  1.9920,  0.3206]])


In [0]:
y.add_(x)
print(y)


tensor([[-0.8518,  1.7260,  0.2071],
        [ 0.7564, -0.4678,  1.2877],
        [-0.5309, -1.5223, -0.3864],
        [ 0.9076, -0.2934,  1.4004],
        [ 0.9390,  1.9920,  0.3206]])


In [0]:
print(x)
print(x[:, 0])

tensor([[-1.0253,  1.6412, -0.4841],
        [ 0.6972, -0.5882,  1.2751],
        [-0.9655, -1.5591, -0.7863],
        [ 0.5113, -0.7911,  1.2207],
        [ 0.5734,  1.7052, -0.0063]])
tensor([-1.0253,  0.6972, -0.9655,  0.5113,  0.5734])


In [0]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8)
print(z)

tensor([[-1.4524, -1.4885,  1.1370, -0.1828],
        [-1.3195,  0.4646,  1.1793, -0.2121],
        [ 0.2088, -0.9322, -0.8098, -1.3215],
        [ 0.2536,  0.3472, -0.1817, -1.0247]])
tensor([-1.4524, -1.4885,  1.1370, -0.1828, -1.3195,  0.4646,  1.1793, -0.2121,
         0.2088, -0.9322, -0.8098, -1.3215,  0.2536,  0.3472, -0.1817, -1.0247])
tensor([[-1.4524, -1.4885,  1.1370, -0.1828, -1.3195,  0.4646,  1.1793, -0.2121],
        [ 0.2088, -0.9322, -0.8098, -1.3215,  0.2536,  0.3472, -0.1817, -1.0247]])


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0969])
1.0969347953796387


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


tensor([2.0969], device='cuda:0')
tensor([2.0969], dtype=torch.float64)
